name: Create DEV Release
on:
  workflow_run:
    workflows: ["[DEV] Build"]
    types:
      - completed

jobs:
  release:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract version from MainPlugin.cs
        id: get_version
        run: |
          VERSION=$(grep -Po 'Version\s*=>\s*new\s*\(\K[0-9]+,[ ]*[0-9]+,[ ]*[0-9]+' RoundReports/MainPlugin.cs | head -n1 | tr -d ' ' | tr ',' '.')
          echo "version=$VERSION-dev" >> $GITHUB_OUTPUT

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: RoundReports
          path: artifact

      - name: Create DEV Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.get_version.outputs.version }}
          name: v${{ steps.get_version.outputs.version }}
          draft: false
          prerelease: true
          files: artifact/RoundReports.dll
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
